{% set name = "dohq-artifactory" %}
{% set version = "0.8.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dohq-artifactory-{{ version }}.tar.gz
  sha256: 4c4e31153a771341cd6d21d766e095701aeddcb2da431b502f357258070b443f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - wheel
  run:
    - pyjwt ~=2.0
    - python >=3.7
    - python-dateutil
    - requests

test:
  imports:
    - dohq_artifactory
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://devopshq.github.io/artifactory/
  summary: A Python interface to Artifactory
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    a live python package for JFrog Artifactory.
  dev_url: https://github.com/devopshq

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/34583

  recipe-maintainers:
    - ianaobi

